context:
  version: "1.3.1"

package:
  name: pinentry
  version: ${{ version }}

source:
  url: https://www.mirrorservice.org/sites/ftp.gnupg.org/gcrypt/pinentry/pinentry-${{ version }}.tar.bz2
  sha256: bc72ee27c7239007ab1896c3c2fae53b076e2c9bd2483dc2769a16902bce8c04

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - autoconf
    - automake
    - gettext-tools
    - make
    - pkg-config
  host:
    - libassuan
    - libgpg-error
    - libtool
    - ncurses
    - if: linux
      then:
        - glib
        - libiconv
        - libsecret
        - zlib

tests:
  - script:
      - pinentry --version

about:
  license: GPL-2.0-only
  license_file: COPYING
  summary: Passphrase entry dialog utilizing the Assuan protocol
  homepage: https://www.gnupg.org/related_software/pinentry/

extra:
  recipe-maintainers:
    - danielnachun
